# fly.toml app configuration file generated for tableslayer-docs on 2024-12-19T23:03:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tableslayer-docs'
primary_region = 'ewr'

[build]
  dockerfile = 'DockerfileDocs'

[env]
  PORT = '8080'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
