# fly.toml app configuration file generated for tableslayer on 2024-12-19T11:18:46-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tableslayer'
primary_region = 'ewr'

[build]
  dockerfile = "DockerfileDev"

[env]
  PORT = '8080'
  BODY_SIZE_LIMIT = "20M"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
