name: PR close preview cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  destroy_resources:
    name: Destroy Vercel Deployment and Turso Database
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/shared
      - name: Install Vercel
        run: pnpm install -g vercel@latest
      - name: Get Preview URL
        uses: dlip/get-vercel-deployment-action@v1.0.2
        id: get-vercel-deployment
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_WEB_PROJECT_ID }}
          github-branch: ${{ github.head_ref }}
          github-commit: ${{ github.event.pull_request.head.sha }}

      - name: Destroy Vercel Deployment
        working-directory: apps/web
        run: |
          vercel remove https://${{ steps.get-vercel-deployment.outputs.deployment-url }} --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_TEAM_ID }} --yes || true

      # Inline deletion of databases for the pull request
      - name: Delete All Turso Databases for the Pull Request
        run: |
          set -e

          # Define variables
          API_BASE_URL="https://api.turso.tech/v1/organizations/snide/databases"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.TURSO_API_TOKEN }}"

          # Extract the PR number from GitHub Actions context
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PREFIX="preview-pr-${PR_NUMBER}"

          # Fetch and delete all databases related to the PR
          DATABASES=$(curl -s -X GET -H "$AUTH_HEADER" "$API_BASE_URL" | jq -r '.databases[] | select(.name | startswith("'"${PREFIX}"'")) | .name')

          for DB_NAME in $DATABASES; do
            HTTP_RESPONSE=$(curl -s -w "\n%{http_code}" -X DELETE \
              -H "$AUTH_HEADER" \
              "$API_BASE_URL/$DB_NAME")

            HTTP_STATUS=$(echo "$HTTP_RESPONSE" | tail -n1)
            RESPONSE=$(echo "$HTTP_RESPONSE" | sed '$d')

            echo "HTTP_STATUS (deleting $DB_NAME): $HTTP_STATUS"
            echo "RESPONSE: $RESPONSE"

            if [ "$HTTP_STATUS" -ne 204 ]; then
              echo "Failed to delete database: $DB_NAME. HTTP Status: $HTTP_STATUS. Response: $RESPONSE"
            else
              echo "Database $DB_NAME deleted successfully."
            fi
          done
