# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      NODE_OPTIONS: '--max-old-space-size=4096'
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Generate .env File
        run: |
          cat <<EOF > apps/web/.env
          TURSO_APP_DB_URL=${{ secrets.TURSO_APP_DB_URL }}
          TURSO_API_TOKEN=${{ secrets.TURSO_API_TOKEN }}
          TURSO_APP_DB_AUTH_TOKEN=${{ secrets.TURSO_APP_DB_AUTH_TOKEN }}
          TURSO_GS_PARENT_DB_URL=${{ secrets.TURSO_GS_PARENT_DB_URL }}
          TURSO_GS_PARENT_DB_AUTH_TOKEN=${{ secrets.TURSO_GS_PARENT_DB_AUTH_TOKEN }}
          RESEND_TOKEN=${{ secrets.RESEND_TOKEN }}
          RESEND_AUDIENCE_ID=${{ secrets.RESEND_AUDIENCE_ID }}
          CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_R2_ACCESS_KEY=${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}
          CLOUDFLARE_R2_SECRET_KEY=${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}
          CLOUDFLARE_R2_BUCKET_NAME=${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}
          CLOUDFLARE_R2_BUCKET_URL=${{ secrets.CLOUDFLARE_R2_BUCKET_URL }}
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          BODY_SIZE_LIMIT=${{ secrets.BODY_SIZE_LIMIT }}
          ENV_NAME=production
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          GITHUB_PR_NUMBER=0
          BASE_URL=https://tableslayer.com
          STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }}
          STRIPE_WEBHOOK_KEY=${{ secrets.STRIPE_WEBHOOK_KEY }}
          STRIPE_PRICE_ID_LIFETIME=${{ secrets.STRIPE_PRICE_ID_LIFETIME }}
          STRIPE_PRICE_ID_MONTHLY=${{ secrets.STRIPE_PRICE_ID_MONTHLY }}
          STRIPE_PRICE_ID_YEARLY=${{ secrets.STRIPE_PRICE_ID_YEARLY }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          PUBLIC_PARTYKIT_HOST=partykit.tableslayer.com
          PARTYKIT_TOKEN=${{ secrets.PARTYKIT_TOKEN }}
          FATHOM_SITE_ID=${{ secrets.FATHOM_SITE_ID }}
          EOF
      - uses: ./.github/shared
      - name: Deploy PartyKit servers
        if: github.ref == 'refs/heads/main'
        working-directory: apps/web
        run: npx partykit deploy --name tableslayer --domain partykit.tableslayer.com
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_KEY }}
          PARTYKIT_TOKEN: ${{ secrets.PARTYKIT_TOKEN }}
          PARTYKIT_LOGIN: ${{ secrets.PARTYKIT_LOGIN }}
      - name: Deploy fly productions
        run: |
          flyctl deploy --remote-only --config fly.web.toml --build-arg NODE_OPTIONS="--max-old-space-size=4096"
          flyctl deploy --remote-only --config fly.docs.toml --build-arg NODE_OPTIONS="--max-old-space-size=4096"
