name: Playwright

on:
  workflow_run:
    workflows: ['Preview DB']
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    needs: [format-check, lint, tsc]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app: docs
          - app: web
    name: ${{ matrix.app }} tests
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/shared
      - name: Display deployment status
        run: 'echo "The deployment URL is https://${{ steps.get-vercel-deployment.outputs.deployment-url }}"'
      - name: Install Playwright Browsers
        if: ${{ github.ref != 'refs/heads/main' }}
        run: pnpx playwright install --with-deps
      - name: Run Playwright Tests
        if: ${{ github.ref != 'refs/heads/main' }}
        working-directory: apps/${{ matrix.app }}
        env:
          BASE_URL: https://web-preview-${{ github.event.pull_request.number }}.vercel.app
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        run: |
          echo "BASE_URL is ${{ env.BASE_URL }}"
          pnpm run test
